### ISSUE TITLE
Number 4

### ISSUE THREAD

**Issue by alexschenider** [gloeyisk/CollectiveFonts#1]
Number 4 on Homescreen Clock Is Bug. They preview a 3 dot on above.

**Comment by gloeyisk** [comment]
> 
> 
> Number 4 on Homescreen Clock Is Bug. They preview a 3 dot on above.

Which font? Could you send me a screenshot so I can check it.
And also which ROM and Android version do you run?

**Comment by gloeyisk** [comment]
> 
> 
> Number 4 on Homescreen Clock Is Bug. They preview a 3 dot on above.

Could you provide screenshot?
